class Params:
    # leagues we have in db
    leagues = [ 'premiere_league', 'la_liga', 'serie-a', 'bundesliga', 'championship','segunda_division', 'serie-b' ]

    # link were we get info
    link_leagues = {'premiere_league': 'https://footystats.org/england/premier-league/fixtures',
                    'la_liga': 'https://footystats.org/spain/la-liga/fixtures',
                    'serie-a': 'https://footystats.org/italy/serie-a/fixtures',
                    'bundesliga': 'https://footystats.org/germany/bundesliga/fixtures',
                    'championship': 'https://footystats.org/england/championship/fixtures',
                    'segunda_division': 'https://footystats.org/spain/segunda-division/fixtures',
                    'serie-b': 'https://footystats.org/italy/serie-b/fixtures'}

    # list unique of teams per league
    list_teams = {'premiere_league': [ 'Norwich City', 'Tottenham Hotspur', 'Watford',
                                       'Brighton & Hove Albion', 'West Ham United', 'AFC Bournemouth',
                                       'Newcastle United', 'Aston Villa', 'Everton', 'Liverpool', 'Arsenal',
                                       'Crystal Palace', 'Sheffield United', 'Southampton', 'Wolverhampton Wanderers',
                                       'Burnley', 'Chelsea', 'Manchester United', 'Leicester City', 'Manchester City' ],
                  'la_liga': [ 'FC Barcelona', 'Real Madrid', 'Atlético Madrid', 'Sevilla FC',
                               'Getafe CF', 'Villarreal', 'Real Sociedad', 'Valencia CF',
                               'Athletic Club Bilbao', 'Granada CF', 'CA Osasuna', 'Levante UD',
                               'Real Betis', 'Real Valladolid', 'Deportivo Alavés',
                               'Celta de Vigo', 'SD Eibar', 'RCD Mallorca', 'Leganés',
                               'RCD Espanyol' ],
                  'serie-a': [ 'Juventus', 'Lazio', 'Inter Milan', 'Atalanta', 'Roma', 'Napoli',
                               'AC Milan', 'Parma', 'Hellas Verona', 'Cagliari', 'Bologna',
                               'Sassuolo', 'Torino', 'Fiorentina', 'Udinese', 'Sampdoria',
                               'Genoa', 'Lecce', 'Brescia', 'SPAL' ],
                  'bundesliga': [ 'Bayern München', 'Borussia Dortmund', 'RB Leipzig',
                                  "Borussia M'gladbach", 'Bayer Leverkusen', 'Hoffenheim',
                                  'Wolfsburg', 'Freiburg', 'Eintracht Frankfurt', 'Hertha BSC',
                                  'Union Berlin', 'Schalke 04', 'Mainz 05', 'Köln', 'Augsburg',
                                  'Werder Bremen', 'Fortuna Düsseldorf', 'Paderborn' ],
                  'championship': [ 'Leeds United', 'West Bromwich Albion', 'Brentford',
                                    'Nottingham Forest', 'Fulham', 'Cardiff City', 'Preston North End',
                                    'Derby County', 'Blackburn Rovers', 'Swansea City', 'Millwall',
                                    'Bristol City', 'Sheffield Wednesday', 'Queens Park Rangers',
                                    'Reading', 'Birmingham City', 'Wigan Athletic',
                                    'Charlton Athletic', 'Middlesbrough', 'Stoke City', 'Hull City',
                                    'Huddersfield Town', 'Luton Town', 'Barnsley' ],
                  'segunda_division': [ 'Cádiz', 'Real Zaragoza', 'SD Huesca', 'Almería', 'Girona FC',
                                        'Elche CF', 'AD Alcorcón', 'Rayo Vallecano', 'CD Tenerife',
                                        'Sporting Gijón', 'Mirandés', 'SD Ponferradina', 'CF Fuenlabrada',
                                        'UD Las Palmas', 'Málaga CF', 'Deportivo La Coruña',
                                        'Albacete Balompié', 'CD Numancia', 'Real Oviedo', 'CD Lugo',
                                        'Extremadura UD', 'Racing Santander' ],
                  'serie-b': [ 'Benevento', 'Crotone', 'Cittadella', 'Spezia', 'Pordenone',
                               'Frosinone', 'Chievo', 'Salernitana', 'Pisa', 'Empoli',
                               'Virtus Entella', 'Perugia', 'Venezia', 'Pescara', 'Juve Stabia',
                               'Cremonese', 'Ascoli', 'Cosenza', 'Trapani', 'Livorno' ]}

    # links were we find odds of previous games
    link_odds = {'premiere_league': 'https://www.football-data.co.uk/mmz4281/1920/E0.csv',
                 'la_liga': 'https://www.football-data.co.uk/mmz4281/1920/SP1.csv',
                 'serie-a': 'https://www.football-data.co.uk/mmz4281/1920/I1.csv',
                 'bundesliga': 'https://www.football-data.co.uk/mmz4281/1920/D1.csv',
                 'championship': 'https://www.football-data.co.uk/mmz4281/1920/E1.csv',
                 'segunda_division': 'https://www.football-data.co.uk/mmz4281/1920/SP2.csv',
                 'serie-b': 'https://www.football-data.co.uk/mmz4281/1920/I2.csv'}

    """dict to link info of previous games to odds df per league
     keys: name of teams in odds data frame
     values: name of teams in games data frame"""
    dict_odds = {'premiere_league': {'Bournemouth': 'AFC Bournemouth',
                                     'Arsenal': 'Arsenal',
                                     'Aston Villa': 'Aston Villa',
                                     'Brighton': 'Brighton & Hove Albion',
                                     'Burnley': 'Burnley',
                                     'Chelsea': 'Chelsea',
                                     'Crystal Palace': 'Crystal Palace',
                                     'Everton': 'Everton',
                                     'Leicester': 'Leicester City',
                                     'Liverpool': 'Liverpool',
                                     'Man City': 'Manchester City',
                                     'Man United': 'Manchester United',
                                     'Newcastle': 'Newcastle United',
                                     'Norwich': 'Norwich City',
                                     'Sheffield United': 'Sheffield United',
                                     'Southampton': 'Southampton',
                                     'Tottenham': 'Tottenham Hotspur',
                                     'Watford': 'Watford',
                                     'West Ham': 'West Ham United',
                                     'Wolves': 'Wolverhampton Wanderers'},
                 'la_liga': {'Ath Bilbao': 'Athletic Club Bilbao',
                             'Ath Madrid': 'Atlético Madrid',
                             'Osasuna': 'CA Osasuna',
                             'Celta': 'Celta de Vigo',
                             'Alaves': 'Deportivo Alavés',
                             'Barcelona': 'FC Barcelona',
                             'Getafe': 'Getafe CF',
                             'Granada': 'Granada CF',
                             'Leganes': 'Leganés',
                             'Levante': 'Levante UD',
                             'Espanol': 'RCD Espanyol',
                             'Mallorca': 'RCD Mallorca',
                             'Betis': 'Real Betis',
                             'Real Madrid': 'Real Madrid',
                             'Sociedad': 'Real Sociedad',
                             'Valladolid': 'Real Valladolid',
                             'Eibar': 'SD Eibar',
                             'Sevilla': 'Sevilla FC',
                             'Valencia': 'Valencia CF',
                             'Villarreal': 'Villarreal'},
                 'serie-a': {'Milan': 'AC Milan',
                             'Atalanta': 'Atalanta',
                             'Bologna': 'Bologna',
                             'Brescia': 'Brescia',
                             'Cagliari': 'Cagliari',
                             'Fiorentina': 'Fiorentina',
                             'Genoa': 'Genoa',
                             'Verona': 'Hellas Verona',
                             'Inter': 'Inter Milan',
                             'Juventus': 'Juventus',
                             'Lazio': 'Lazio',
                             'Lecce': 'Lecce',
                             'Napoli': 'Napoli',
                             'Parma': 'Parma',
                             'Roma': 'Roma',
                             'Spal': 'SPAL',
                             'Sampdoria': 'Sampdoria',
                             'Sassuolo': 'Sassuolo',
                             'Torino': 'Torino',
                             'Udinese': 'Udinese'},
                 'bundesliga': {'Augsburg': 'Augsburg',
                                'Bayern Munich': 'Bayern München',
                                'Dortmund': 'Borussia Dortmund',
                                'Ein Frankfurt': 'Eintracht Frankfurt',
                                'FC Koln': 'Köln',
                                'Fortuna Dusseldorf': 'Fortuna Düsseldorf',
                                'Freiburg': 'Freiburg',
                                'Hertha': 'Hertha BSC',
                                'Hoffenheim': 'Hoffenheim',
                                'Leverkusen': 'Bayer Leverkusen',
                                "M'gladbach": "Borussia M'gladbach",
                                'Mainz': 'Mainz 05',
                                'Paderborn': 'Paderborn',
                                'RB Leipzig': 'RB Leipzig',
                                'Schalke 04': 'Schalke 04',
                                'Union Berlin': 'Union Berlin',
                                'Werder Bremen': 'Werder Bremen',
                                'Wolfsburg': 'Wolfsburg'},
                 'championship': {'Barnsley': 'Barnsley',
                                  'Birmingham': 'Birmingham City',
                                  'Blackburn': 'Blackburn Rovers',
                                  'Brentford': 'Brentford',
                                  'Bristol City': 'Bristol City',
                                  'Cardiff': 'Cardiff City',
                                  'Charlton': 'Charlton Athletic',
                                  'Derby': 'Derby County',
                                  'Fulham': 'Fulham',
                                  'Huddersfield': 'Huddersfield Town',
                                  'Hull': 'Hull City',
                                  'Leeds': 'Leeds United',
                                  'Luton': 'Luton Town',
                                  'Middlesbrough': 'Middlesbrough',
                                  'Millwall': 'Millwall',
                                  "Nott'm Forest": 'Nottingham Forest',
                                  'Preston': 'Preston North End',
                                  'QPR': 'Queens Park Rangers',
                                  'Reading': 'Reading',
                                  'Sheffield Weds': 'Sheffield Wednesday',
                                  'Stoke': 'Stoke City',
                                  'Swansea': 'Swansea City',
                                  'West Brom': 'West Bromwich Albion',
                                  'Wigan': 'Wigan Athletic'},
                 'segunda_division': {'Albacete': 'Albacete Balompié',
                                      'Alcorcon': 'AD Alcorcón',
                                      'Almeria': 'Almería',
                                      'Cadiz': 'Cádiz',
                                      'Elche': 'Elche CF',
                                      'Extremadura UD': 'Extremadura UD',
                                      'Fuenlabrada': 'CF Fuenlabrada',
                                      'Girona': 'Girona FC',
                                      'Huesca': 'SD Huesca',
                                      'La Coruna': 'Deportivo La Coruña',
                                      'Las Palmas': 'UD Las Palmas',
                                      'Lugo': 'CD Lugo',
                                      'Malaga': 'Mirandés',
                                      'Mirandes': 'Málaga CF',
                                      'Numancia': 'CD Numancia',
                                      'Oviedo': 'Real Oviedo',
                                      'Ponferradina': 'SD Ponferradina',
                                      'Santander': 'Racing Santander',
                                      'Sp Gijon': 'Sporting Gijón',
                                      'Tenerife': 'CD Tenerife',
                                      'Vallecano': 'Rayo Vallecano',
                                      'Zaragoza': 'Real Zaragoza'},
                 'serie-b': {'Ascoli': 'Ascoli',
                             'Benevento': 'Benevento',
                             'Chievo': 'Chievo',
                             'Cittadella': 'Cittadella',
                             'Cosenza': 'Cosenza',
                             'Cremonese': 'Cremonese',
                             'Crotone': 'Crotone',
                             'Empoli': 'Empoli',
                             'Frosinone': 'Frosinone',
                             'Juve Stabia': 'Juve Stabia',
                             'Livorno': 'Livorno',
                             'Perugia': 'Perugia',
                             'Pescara': 'Pescara',
                             'Pisa': 'Pisa',
                             'Pordenone': 'Pordenone',
                             'Salernitana': 'Salernitana',
                             'Spezia': 'Spezia',
                             'Trapani': 'Trapani',
                             'Venezia': 'Venezia',
                             'Virtus Entella': 'Virtus Entella'}}

    # links were we find odds of next games
    link_odds_next = {'premiere_league': 'https://www.betexplorer.com/soccer/england/premier-league/',
                      'la_liga': 'https://www.betexplorer.com/soccer/spain/laliga/',
                      'serie-a': 'https://www.betexplorer.com/soccer/italy/serie-a/',
                      'bundesliga': 'https://www.betexplorer.com/soccer/germany/bundesliga/',
                      'championship': 'https://www.betexplorer.com/soccer/england/championship/',
                      'segunda_division': 'https://www.betexplorer.com/soccer/spain/laliga2/',
                      'serie-b': 'https://www.betexplorer.com/soccer/italy/serie-b/'
                      }

    """dict to link info of next games to odds df per league
         keys: name of teams in games data frame
         values: name of teams in odds data frame"""
    dict_odds_next = {'premiere_league': {'Arsenal': 'Arsenal',
                                          'Aston Villa': 'Aston Villa',
                                          'AFC Bournemouth': 'Bournemouth',
                                          'Brighton & Hove Albion': 'Brighton',
                                          'Burnley': 'Burnley',
                                          'Chelsea': 'Chelsea',
                                          'Crystal Palace': 'Crystal Palace',
                                          'Everton': 'Everton',
                                          'Leicester City': 'Leicester',
                                          'Liverpool': 'Liverpool',
                                          'Manchester City': 'Manchester City',
                                          'Manchester United': 'Manchester Utd',
                                          'Norwich City': 'Norwich',
                                          'Newcastle United': 'Newcastle',
                                          'Sheffield United': 'Sheffield Utd',
                                          'Southampton': 'Southampton',
                                          'Tottenham Hotspur': 'Tottenham',
                                          'Watford': 'Watford',
                                          'West Ham United': 'West Ham',
                                          'Wolverhampton Wanderers': 'Wolves'},
                      'la_liga': {'Athletic Club Bilbao': 'Ath Bilbao',
                                  'Atlético Madrid': 'Atl. Madrid',
                                  'CA Osasuna': 'Osasuna',
                                  'Celta de Vigo': 'Celta Vigo',
                                  'Deportivo Alavés': 'Alaves',
                                  'FC Barcelona': 'Barcelona',
                                  'Getafe CF': 'Getafe',
                                  'Granada CF': 'Granada CF',
                                  'Leganés': 'Leganes',
                                  'Levante UD': 'Levante',
                                  'RCD Espanyol': 'Espanyol',
                                  'RCD Mallorca': 'Mallorca',
                                  'Real Betis': 'Betis',
                                  'Real Madrid': 'Real Madrid',
                                  'Real Sociedad': 'Real Sociedad',
                                  'Real Valladolid': 'Valladolid',
                                  'SD Eibar': 'Eibar',
                                  'Sevilla FC': 'Sevilla',
                                  'Valencia CF': 'Valencia',
                                  'Villarreal': 'Villarreal'},
                      'serie-a': {'AC Milan': 'AC Milan',
                                  'Atalanta': 'Atalanta',
                                  'Bologna': 'Bologna',
                                  'Brescia': 'Brescia',
                                  'Cagliari': 'Cagliari',
                                  'Fiorentina': 'Fiorentina',
                                  'Genoa': 'Genoa',
                                  'Hellas Verona': 'Verona',
                                  'Inter Milan': 'Inter',
                                  'Juventus': 'Juventus',
                                  'Lazio': 'Lazio',
                                  'Lecce': 'Lecce',
                                  'Napoli': 'Napoli',
                                  'Parma': 'Parma',
                                  'Roma': 'AS Roma',
                                  'SPAL': 'Spal',
                                  'Sampdoria': 'Sampdoria',
                                  'Sassuolo': 'Sassuolo',
                                  'Torino': 'Torino',
                                  'Udinese': 'Udinese'},
                      'bundesliga': {'Augsburg': 'Augsburg',
                                     'Bayer Leverkusen': 'Bayer Leverkusen',
                                     'Bayern München': 'Bayern Munich',
                                     'Borussia Dortmund': 'Dortmund',
                                     "Borussia M'gladbach": 'B. Monchengladbach',
                                     'Eintracht Frankfurt': 'Eintracht Frankfurt',
                                     'Fortuna Düsseldorf': 'Dusseldorf',
                                     'Freiburg': 'Freiburg',
                                     'Hertha BSC': 'Hertha Berlin',
                                     'Hoffenheim': 'Hoffenheim',
                                     'Köln': 'FC Koln',
                                     'Mainz 05': 'Mainz',
                                     'Paderborn': 'Paderborn',
                                     'RB Leipzig': 'RB Leipzig',
                                     'Schalke 04': 'Schalke',
                                     'Union Berlin': 'Union Berlin',
                                     'Werder Bremen': 'Werder Bremen',
                                     'Wolfsburg': 'Wolfsburg'},
                      'championship': {'Barnsley': 'Barnsley',
                                       'Birmingham City': 'Birmingham',
                                       'Blackburn Rovers': 'Blackburn',
                                       'Brentford': 'Brentford',
                                       'Bristol City': 'Bristol City',
                                       'Cardiff City': 'Cardiff',
                                       'Charlton Athletic': 'Charlton',
                                       'Derby County': 'Derby',
                                       'Fulham': 'Fulham',
                                       'Huddersfield Town': 'Huddersfield',
                                       'Hull City': 'Hull',
                                       'Leeds United': 'Leeds',
                                       'Luton Town': 'Luton',
                                       'Middlesbrough': 'Middlesbrough',
                                       'Millwall': 'Millwall',
                                       'Nottingham Forest': 'Nottingham',
                                       'Preston North End': 'Preston',
                                       'Queens Park Rangers': 'QPR',
                                       'Reading': 'Reading',
                                       'Sheffield Wednesday': 'Sheffield Wed',
                                       'Stoke City': 'Stoke',
                                       'Swansea City': 'Swansea',
                                       'West Bromwich Albion': 'West Brom',
                                       'Wigan Athletic': 'Wigan'},
                      'segunda_division': {'AD Alcorcón': 'Alcorcon',
                                           'Albacete Balompié': 'Albacete',
                                           'Almería': 'Almeria',
                                           'CD Lugo': 'Lugo',
                                           'CD Numancia': 'Numancia',
                                           'CD Tenerife': 'Tenerife',
                                           'CF Fuenlabrada': 'Fuenlabrada',
                                           'Cádiz': 'Cadiz CF',
                                           'Deportivo La Coruña': 'Dep. La Coruna',
                                           'Elche CF': 'Elche',
                                           'Extremadura UD': 'Extremadura UD',
                                           'Girona FC': 'Girona',
                                           'Mirandés': 'Mirandes',
                                           'Málaga CF': 'Malaga',
                                           'Racing Santander': 'Racing Santander',
                                           'Rayo Vallecano': 'Rayo Vallecano',
                                           'Real Oviedo': 'R. Oviedo',
                                           'Real Zaragoza': 'Zaragoza',
                                           'SD Huesca': 'Huesca',
                                           'SD Ponferradina': 'Ponferradina',
                                           'Sporting Gijón': 'Gijon',
                                           'UD Las Palmas': 'Las Palmas'},
                      'serie-b': {'Ascoli': 'Ascoli',
                                 'Benevento': 'Benevento',
                                 'Chievo': 'Chievo',
                                 'Cittadella': 'Cittadella',
                                 'Cosenza': 'Cosenza',
                                 'Cremonese': 'Cremonese',
                                 'Crotone': 'Crotone',
                                 'Empoli': 'Empoli',
                                 'Frosinone': 'Frosinone',
                                 'Juve Stabia': 'Juve Stabia',
                                 'Livorno': 'Livorno',
                                 'Perugia': 'Perugia',
                                 'Pescara': 'Pescara',
                                 'Pisa': 'Pisa',
                                 'Pordenone': 'Pordenone',
                                 'Salernitana': 'Salernitana',
                                 'Spezia': 'Spezia',
                                 'Trapani': 'Trapani',
                                 'Venezia': 'Venezia',
                                 'Virtus Entella': 'Entella'}}
