class Params:
    leagues = ['premiere_league', 'la_liga', 'serie-a', 'bundesliga']

    link_leagues = {'premiere_league': 'https://footystats.org/england/premier-league/fixtures',
                    'la_liga': 'https://footystats.org/spain/la-liga/fixtures',
                    'serie-a': 'https://footystats.org/italy/serie-a/fixtures',
                    'bundesliga': 'https://footystats.org/germany/bundesliga/fixtures'}

    list_teams = {'premiere_league': [ 'Norwich City', 'Tottenham Hotspur', 'Watford',
                                       'Brighton & Hove Albion', 'West Ham United', 'AFC Bournemouth',
                                       'Newcastle United', 'Aston Villa', 'Everton', 'Liverpool', 'Arsenal',
                                       'Crystal Palace', 'Sheffield United', 'Southampton', 'Wolverhampton Wanderers',
                                       'Burnley', 'Chelsea', 'Manchester United', 'Leicester City', 'Manchester City' ],
                  'la_liga': [ 'FC Barcelona', 'Real Madrid', 'Atlético Madrid', 'Sevilla FC',
                               'Getafe CF', 'Villarreal', 'Real Sociedad', 'Valencia CF',
                               'Athletic Club Bilbao', 'Granada CF', 'CA Osasuna', 'Levante UD',
                               'Real Betis', 'Real Valladolid', 'Deportivo Alavés',
                               'Celta de Vigo', 'SD Eibar', 'RCD Mallorca', 'Leganés',
                               'RCD Espanyol' ],
                  'serie-a': [ 'Juventus', 'Lazio', 'Inter Milan', 'Atalanta', 'Roma', 'Napoli',
                               'AC Milan', 'Parma', 'Hellas Verona', 'Cagliari', 'Bologna',
                               'Sassuolo', 'Torino', 'Fiorentina', 'Udinese', 'Sampdoria',
                               'Genoa', 'Lecce', 'Brescia', 'SPAL' ],
                  'bundesliga': [ 'Bayern München', 'Borussia Dortmund', 'RB Leipzig',
                                  "Borussia M'gladbach", 'Bayer Leverkusen', 'Hoffenheim',
                                  'Wolfsburg', 'Freiburg', 'Eintracht Frankfurt', 'Hertha BSC',
                                  'Union Berlin', 'Schalke 04', 'Mainz 05', 'Köln', 'Augsburg',
                                  'Werder Bremen', 'Fortuna Düsseldorf', 'Paderborn' ]}


    link_odds = {'premiere_league': 'https://www.football-data.co.uk/mmz4281/1920/E0.csv',
                 'la_liga': 'https://www.football-data.co.uk/mmz4281/1920/SP1.csv',
                 'serie-a': 'https://www.football-data.co.uk/mmz4281/1920/I1.csv',
                 'bundesliga': 'https://www.football-data.co.uk/mmz4281/1920/D1.csv'}

    dict_odds = {'premiere_league': {'Bournemouth': 'AFC Bournemouth',
                                     'Arsenal': 'Arsenal',
                                     'Aston Villa': 'Aston Villa',
                                     'Brighton': 'Brighton & Hove Albion',
                                     'Burnley': 'Burnley',
                                     'Chelsea': 'Chelsea',
                                     'Crystal Palace': 'Crystal Palace',
                                     'Everton': 'Everton',
                                     'Leicester': 'Leicester City',
                                     'Liverpool': 'Liverpool',
                                     'Man City': 'Manchester City',
                                     'Man United': 'Manchester United',
                                     'Newcastle': 'Newcastle United',
                                     'Norwich': 'Norwich City',
                                     'Sheffield United': 'Sheffield United',
                                     'Southampton': 'Southampton',
                                     'Tottenham': 'Tottenham Hotspur',
                                     'Watford': 'Watford',
                                     'West Ham': 'West Ham United',
                                     'Wolves': 'Wolverhampton Wanderers'},
                 'la_liga': {'Ath Bilbao': 'Athletic Club Bilbao',
                             'Ath Madrid': 'Atlético Madrid',
                             'Osasuna': 'CA Osasuna',
                             'Celta': 'Celta de Vigo',
                             'Alaves': 'Deportivo Alavés',
                             'Barcelona': 'FC Barcelona',
                             'Getafe': 'Getafe CF',
                             'Granada': 'Granada CF',
                             'Leganes': 'Leganés',
                             'Levante': 'Levante UD',
                             'Espanol': 'RCD Espanyol',
                             'Mallorca': 'RCD Mallorca',
                             'Betis': 'Real Betis',
                             'Real Madrid': 'Real Madrid',
                             'Sociedad': 'Real Sociedad',
                             'Valladolid': 'Real Valladolid',
                             'Eibar': 'SD Eibar',
                             'Sevilla': 'Sevilla FC',
                             'Valencia': 'Valencia CF',
                             'Villarreal': 'Villarreal'},
                 'serie-a': {'Milan': 'AC Milan',
                             'Atalanta': 'Atalanta',
                             'Bologna': 'Bologna',
                             'Brescia': 'Brescia',
                             'Cagliari': 'Cagliari',
                             'Fiorentina': 'Fiorentina',
                             'Genoa': 'Genoa',
                             'Verona': 'Hellas Verona',
                             'Inter': 'Inter Milan',
                             'Juventus': 'Juventus',
                             'Lazio': 'Lazio',
                             'Lecce': 'Lecce',
                             'Napoli': 'Napoli',
                             'Parma': 'Parma',
                             'Roma': 'Roma',
                             'Spal': 'SPAL',
                             'Sampdoria': 'Sampdoria',
                             'Sassuolo': 'Sassuolo',
                             'Torino': 'Torino',
                             'Udinese': 'Udinese'},
                 'bundesliga': {'Augsburg': 'Augsburg',
                                'Bayern Munich': 'Bayern München',
                                'Dortmund': 'Borussia Dortmund',
                                'Ein Frankfurt': 'Eintracht Frankfurt',
                                'FC Koln': 'Köln',
                                'Fortuna Dusseldorf': 'Fortuna Düsseldorf',
                                'Freiburg': 'Freiburg',
                                'Hertha': 'Hertha BSC',
                                'Hoffenheim': 'Hoffenheim',
                                'Leverkusen': 'Bayer Leverkusen',
                                "M'gladbach": "Borussia M'gladbach",
                                'Mainz': 'Mainz 05',
                                'Paderborn': 'Paderborn',
                                'RB Leipzig': 'RB Leipzig',
                                'Schalke 04': 'Schalke 04',
                                'Union Berlin': 'Union Berlin',
                                'Werder Bremen': 'Werder Bremen',
                                'Wolfsburg': 'Wolfsburg'}}


    link_odds_next = {'premiere_league': 'https://www.betexplorer.com/soccer/england/premier-league/',
                      'la_liga': 'https://www.betexplorer.com/soccer/spain/laliga/',
                      'serie-a': 'https://www.betexplorer.com/soccer/italy/serie-a/',
                      'bundesliga': 'https://www.betexplorer.com/soccer/germany/bundesliga/'}

    dict_odds_next = {'premiere_league': {'Arsenal': 'Arsenal',
                                          'Aston Villa': 'Aston Villa',
                                          'AFC Bournemouth': 'Bournemouth',
                                          'Brighton & Hove Albion': 'Brighton',
                                          'Burnley': 'Burnley',
                                          'Chelsea': 'Chelsea',
                                          'Crystal Palace': 'Crystal Palace',
                                          'Everton': 'Everton',
                                          'Leicester City': 'Leicester',
                                          'Liverpool': 'Liverpool',
                                          'Manchester City': 'Manchester City',
                                          'Manchester United': 'Manchester Utd',
                                          'Norwich City': 'Norwich',
                                          'Newcastle United': 'Newcastle',
                                          'Sheffield United': 'Sheffield Utd',
                                          'Southampton': 'Southampton',
                                          'Tottenham Hotspur': 'Tottenham',
                                          'Watford': 'Watford',
                                          'West Ham United': 'West Ham',
                                          'Wolverhampton Wanderers': 'Wolves'},
                      'la_liga': {'Athletic Club Bilbao': 'Ath Bilbao',
                                  'Atlético Madrid': 'Atl. Madrid',
                                  'CA Osasuna': 'Osasuna',
                                  'Celta de Vigo': 'Celta Vigo',
                                  'Deportivo Alavés': 'Alaves',
                                  'FC Barcelona': 'Barcelona',
                                  'Getafe CF': 'Getafe',
                                  'Granada CF': 'Granada CF',
                                  'Leganés': 'Leganes',
                                  'Levante UD': 'Levante',
                                  'RCD Espanyol': 'Espanyol',
                                  'RCD Mallorca': 'Mallorca',
                                  'Real Betis': 'Betis',
                                  'Real Madrid': 'Real Madrid',
                                  'Real Sociedad': 'Real Sociedad',
                                  'Real Valladolid': 'Valladolid',
                                  'SD Eibar': 'Eibar',
                                  'Sevilla FC': 'Sevilla',
                                  'Valencia CF': 'Valencia',
                                  'Villarreal': 'Villarreal'},
                      'serie-a': {'AC Milan': 'AC Milan',
                                  'Atalanta': 'Atalanta',
                                  'Bologna': 'Bologna',
                                  'Brescia': 'Brescia',
                                  'Cagliari': 'Cagliari',
                                  'Fiorentina': 'Fiorentina',
                                  'Genoa': 'Genoa',
                                  'Hellas Verona': 'Verona',
                                  'Inter Milan': 'Inter',
                                  'Juventus': 'Juventus',
                                  'Lazio': 'Lazio',
                                  'Lecce': 'Lecce',
                                  'Napoli': 'Napoli',
                                  'Parma': 'Parma',
                                  'Roma': 'AS Roma',
                                  'SPAL': 'Spal',
                                  'Sampdoria': 'Sampdoria',
                                  'Sassuolo': 'Sassuolo',
                                  'Torino': 'Torino',
                                  'Udinese': 'Udinese'},
                      'bundesliga': {'Augsburg': 'Augsburg',
                                      'Bayer Leverkusen':'Bayer Leverkusen',
                                      'Bayern München': 'Bayern Munich',
                                      'Borussia Dortmund': 'Dortmund',
                                      "Borussia M'gladbach": 'B. Monchengladbach',
                                      'Eintracht Frankfurt': 'Eintracht Frankfurt',
                                      'Fortuna Düsseldorf': 'Dusseldorf',
                                      'Freiburg': 'Freiburg',
                                      'Hertha BSC': 'Hertha Berlin',
                                      'Hoffenheim': 'Hoffenheim',
                                      'Köln': 'FC Koln',
                                      'Mainz 05': 'Mainz',
                                      'Paderborn': 'Paderborn',
                                      'RB Leipzig': 'RB Leipzig',
                                      'Schalke 04': 'Schalke',
                                      'Union Berlin': 'Union Berlin',
                                      'Werder Bremen': 'Werder Bremen',
                                      'Wolfsburg': 'Wolfsburg'}}
